development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://wwualbjhfgxjwc:a747df05df756e2d91ecf0306c1a9a342286c47d8c2a8ea02b8ca92a11f61e01@ec2-23-23-248-247.compute-1.amazonaws.com:5432/dc7mpjgoed7ro4
  channel_prefix: FirstApp_production
